### PR TITLE
New Asset: Rock_1 & Cleaned Asset: player.png

### PR DESCRIPTION
**Pull request by mamarilmanson**
Please add this asset as you like. I don't know how to add a custom lightoccluder and collisionshape. :(

More iterations of this will be done to create variety... :)

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I guess I'll wait until you make the iterations/different shapes/etc. and then I'll merge to decrease the amount of merge requests (and clutter), fine?

**Comment by mamarilmanson** [comment]
yes... sure... :)

**Comment by akien-mga** [comment]
It looks really cool, keep up the good work :)

**Comment by mamarilmanson** [comment]
I might still change this when I have the complete set... :)

**Comment by bojidar-bg** [comment]
@mamarilmanson BTW, you can merge this yourself now :smile:

**Comment by mamarilmanson** [comment]
Maybe later... I'm still conceptualizing on the next art to add on the game... :)

**Pull request merged**
