### PR TITLE
Experimental spider eye particle effect

### PR DESCRIPTION
**Pull request by her001**
An attempt to address #31, still needs some work/feedback.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@her001 Can you give a screenshot?

**Comment by her001** [comment]
Yes 

screenshot_2015-10-19_08-59-23

Right now only enemy 1 is implemented, until it is decided if this is a good implementation or not. It emits particles from the eyes, which should have almost no effect on performance. The particles are set to additive blend mode, so they show up in the dark. They stay in position relative to the world, so the streaks are left where the spider was walking, and streak further if the spider is moving faster. Biggest problem for now: Need to adjust parameters until there is enough particles to make it look connected, or use a texture which is longer.

**Comment by bojidar-bg** [comment]
I think it is better not to use too much particles, so maybe a longer texture will work better.

BTW, you can try to make an option for the amount of particles, and change it from script in _ready() if you want to...

**Comment by her001** [comment]
Only problem with a longer texture: When it sits still, there will still be a streak when there shouldn't be.

**Comment by bojidar-bg** [comment]
Yeah, it will be a problem...
Maybe this will be helpful? https://github.com/LeonardMeagher2/Godot-Assets/blob/master/Scenes/2DTrail.gd

**Comment by her001** [comment]
You are right, this might not be the best implementation for the godot engine. It appears that opaque, additive particles are not as efficient as I expected. I just did some performance tests and they are not favorable, assuming you want for it to be possible to have lots of enemies on screen.

**Comment by mamarilmanson** [comment]
Maybe something like this in which it fades away and disappears...
untitled-1

**Pull request closed without merging**
